theme: jekyll-theme-minimal
title: Carla's Awesome Portfolio
author: Clairefox
email: claire.2007@live.com
logo: /assets/img/logo.png
show_downloads: false
google_analytics: 

description: Welcome to my treasure trove of heckin cool code n stuff!

# social links
twitter_username: Teh_Carla # DO NOT include the @ character, or else the build will fail!
github_username:  clairefox # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
