theme: jekyll-theme-minimal
title: Carla's Awesome Portfolio
author: Clairefox
email: claire.2007@live.com
logo: /assets/img/logo.png
show_downloads: false
google_analytics: 

description: Welcome to my treasure trove of heckin cool code n stuff!

# social links
social_links:
  twitter: 
  github: clairefox
  stackoverflow: "4885230"
  facebook: 
  instagram: 
  linkedin: carlayoung07
  pinterest: 


show_excerpts: true # set to false to remove excerpts on the homepage